server:
  port: 8384
---
spring:
  profiles:
  active: h2
---
logging:
  config: classpath:logconfig/log4j2.xml

#spring.jpa.show-sql=true
#logging.level.org.springframework=debug
#############################  H2  #################################
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#############################  Oracle #########################3
#spring.jpa.hibernate.ddl-auto=update
# Oracle settings
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
#spring.datasource.username=naveen
#spring.datasource.password=mishra
#spring.datasource.driverClassName=oracle.jdbc.driver.OracleDriver
#spring.jpa.database-platform=
